import Foundation

public enum JunkCategory: String, CaseIterable {
    case derivedData = "DerivedData"
    case archives = "Archives"
    case iOSDeviceSupport = "iOS DeviceSupport"
    case watchOSDeviceSupport = "watchOS DeviceSupport"
    case tvOSDeviceSupport = "tvOS DeviceSupport"
    case simulatorDevices = "Simulator Devices"
    case simulatorCaches = "Simulator Caches"
    case xcodeCaches = "Xcode Caches"
    case spmCaches = "Swift Package Manager Caches"
    case deviceLogs = "Device Logs"
    case userSimulatorRuntimes = "User Simulator Runtimes"
    case cocoaPodsCache = "CocoaPods Cache"
    case carthageCache = "Carthage Cache"
    case simulatorLogs = "Simulator Logs"
    case playgroundTemp = "Playground Temporary Files"
    case mobileDeviceCrashLogs = "MobileDevice Crash Logs"
    
    public var displayName: String {
        switch self {
        case .derivedData: return "Derived Data"
        case .archives: return "Archives"
        case .iOSDeviceSupport: return "iOS DeviceSupport"
        case .watchOSDeviceSupport: return "watchOS DeviceSupport"
        case .tvOSDeviceSupport: return "tvOS DeviceSupport"
        case .simulatorDevices: return "Simulator Devices"
        case .simulatorCaches: return "Simulator Caches"
        case .xcodeCaches: return "Xcode Caches"
        case .spmCaches: return "Swift Package Manager Caches"
        case .deviceLogs: return "Device Logs"
        case .userSimulatorRuntimes: return "User Simulator Runtimes"
        case .cocoaPodsCache: return "CocoaPods Cache"
        case .carthageCache: return "Carthage Cache"
        case .simulatorLogs: return "Simulator Logs"
        case .playgroundTemp: return "Playground Temporary Files"
        case .mobileDeviceCrashLogs: return "MobileDevice Crash Logs"
        }
    }
    
    public var relativePath: String {
        switch self {
        case .derivedData:
            return "Library/Developer/Xcode/DerivedData"
        case .archives:
            return "Library/Developer/Xcode/Archives"
        case .iOSDeviceSupport:
            return "Library/Developer/Xcode/iOS DeviceSupport"
        case .watchOSDeviceSupport:
            return "Library/Developer/Xcode/watchOS DeviceSupport"
        case .tvOSDeviceSupport:
            return "Library/Developer/Xcode/tvOS DeviceSupport"
        case .simulatorDevices:
            return "Library/Developer/CoreSimulator/Devices"
        case .simulatorCaches:
            return "Library/Developer/CoreSimulator/Caches"
        case .xcodeCaches:
            return "Library/Caches/com.apple.dt.Xcode"
        case .spmCaches:
            return "Library/Caches/org.swift.swiftpm"
        case .deviceLogs:
            return "Library/Developer/Xcode/DeviceLogs"
        case .userSimulatorRuntimes:
            return "Library/Developer/Developer/CoreSimulator/Profiles/Runtimes"
        case .cocoaPodsCache:
            return "Library/Caches/CocoaPods"
        case .carthageCache:
            return "Library/Caches/org.carthage.CarthageKit"
        case .simulatorLogs:
            return "Library/Logs/CoreSimulator"
        case .playgroundTemp:
            return "Library/Developer/Xcode/UserData/PlaygroundTemp"
        case .mobileDeviceCrashLogs:
            return "Library/Logs/CrashReporter/MobileDevice"
        }
    }
    
    public var description: String {
        switch self {
        case .derivedData:
            return "Build output, indexes, and intermediate files. Xcode will rebuild them."
        case .archives:
            return "App store distribution builds. You will lose historical archives (used for crash symbolication)."
        case .iOSDeviceSupport:
            return "Debugging symbols for iOS devices. Xcode regenerates them when devices connect."
        case .watchOSDeviceSupport:
            return "Debugging symbols for watchOS devices."
        case .tvOSDeviceSupport:
            return "Debugging symbols for tvOS devices."
        case .simulatorDevices:
            return "Simulated device files. Resets simulator settings and deletes app documents/states."
        case .simulatorCaches:
            return "Cache files generated by active or past simulator sessions."
        case .xcodeCaches:
            return "Xcode internal caches and temporary files."
        case .spmCaches:
            return "SPM dependency clones and checkout caches. Swift builds will re-fetch them."
        case .deviceLogs:
            return "Synced crash logs from connected physical devices."
        case .userSimulatorRuntimes:
            return "Downloaded OS runtimes. Deleting will remove these OS versions from simulator options."
        case .cocoaPodsCache:
            return "Cached CocoaPods library downloads and repository specifications."
        case .carthageCache:
            return "Carthage dependency downloads and pre-built binaries."
        case .simulatorLogs:
            return "Developer log files produced by iOS simulators."
        case .playgroundTemp:
            return "Xcode Swift Playground temporary execution cache."
        case .mobileDeviceCrashLogs:
            return "Crash reports synced from connected physical devices."
        }
    }
    
    public var isSafe: Bool {
        switch self {
        case .archives, .simulatorDevices, .userSimulatorRuntimes:
            return false // Deleting these requires caution / resets simulator setups or runtimes
        default:
            return true
        }
    }
    
    public var url: URL {
        let home = FileManager.default.homeDirectoryForCurrentUser
        return home.appendingPathComponent(relativePath)
    }
    
    public var exists: Bool {
        return FileManager.default.fileExists(atPath: url.path)
    }
    
    /// Calculates directory size recursively in bytes.
    public func calculateSize() -> Int64 {
        let path = url.path
        var isDir: ObjCBool = false
        guard FileManager.default.fileExists(atPath: path, isDirectory: &isDir) else {
            return 0
        }
        
        if !isDir.boolValue {
            do {
                let attrs = try FileManager.default.attributesOfItem(atPath: path)
                return attrs[.size] as? Int64 ?? 0
            } catch {
                return 0
            }
        }
        
        var totalSize: Int64 = 0
        let properties: [URLResourceKey] = [.fileSizeKey, .isDirectoryKey]
        
        guard let enumerator = FileManager.default.enumerator(
            at: url,
            includingPropertiesForKeys: properties,
            options: [.skipsHiddenFiles],
            errorHandler: nil
        ) else {
            return 0
        }
        
        for case let fileURL as URL in enumerator {
            do {
                let values = try fileURL.resourceValues(forKeys: Set(properties))
                if let isDirectory = values.isDirectory, !isDirectory {
                    if let fileSize = values.fileSize {
                        totalSize += Int64(fileSize)
                    }
                }
            } catch {
                // Ignore individual file errors to continue scanning remaining files
            }
        }
        
        return totalSize
    }
    
    /// Deletes the folder and its contents recursively.
    public func delete() throws {
        let fm = FileManager.default
        guard fm.fileExists(atPath: url.path) else { return }
        try fm.removeItem(at: url)
    }
    
    /// Helper to format bytes to human readable string
    public static func formatBytes(_ bytes: Int64) -> String {
        let kb = Double(bytes) / 1024.0
        let mb = kb / 1024.0
        let gb = mb / 1024.0
        
        if gb >= 1.0 {
            return String(format: "%.2f GB", gb)
        } else if mb >= 1.0 {
            return String(format: "%.2f MB", mb)
        } else if kb >= 1.0 {
            return String(format: "%.2f KB", kb)
        } else {
            return "\(bytes) B"
        }
    }
}
